import 'package:flutter/material.dart';

class MyColors{
  // static const Color primaryColor = Color(0xff1DA1F2);
  static const Color primaryColor = Color(0xff38003C);
  static const Color backgroundColor = Color(0xffF2F3F5);
  static const Color boxBackgroundColor = Color(0xffffffff);
  static const Color boxBorderColor = Color(0xffE7E7E7);
  static const Color receivedChatColor = Color(0xffCCE3D3);
  static const Color beigeColor = Color(0xffF7EFE6);
  static const Color lightblue = Color(0xffC9F7FF);
  static const Color purple = Color(0xff38003C);
  static const Color blue = Color(0xff0097FF);
  static const Color blue2 = Color(0xff567FFF);
  static const Color blue3 = Color(0xffE5FBFF);
  static const Color grey1 = Color(0xffA7A7A7);
  static const Color grey2 = Color(0xff888888);
  static const Color grey3 = Color(0xffF4F4F5);
  static const Color grey4 = Color(0xffECECEC);
  static const Color grey5 = Color(0xff41474D);
  static const Color grey6 = Color(0xff4B5563);
  static const Color grey7 = Color(0xff7C7C7C);
  static const Color grey8 = Color(0xffD9D9D9);
  static const Color grey9 = Color(0xff999999);
  static const Color grey10 = Color(0xff6B7280);
  static const Color grey11 = Color(0xff595959);
  static const Color grey12 = Color(0xff454545);
  static const Color box1 = Color(0xffF1F1F1);
  static const Color lightgreen = Color(0xff0DC7B0);
  static const Color green = Color(0xff28990C);
  static const Color green2 = Color(0xff48B771);
  static const Color green3 = Color(0xff0E9F8E);
  static const Color green4 = Color(0xff4EAE70);
  static const Color lightOrange = Color(0xffFD8A04);
  static const Color orange1 = Color(0xffFFA338);
  static const Color hintColor = Color(0xff555555);
  static const Color red1 = Color(0xffD74837);
  static const Color red2 = Color(0xffC21E0B);
  static const Color red3 = Color(0xffFF2F2F);
  static const Color whiteColor = Colors.white;
  static const Color redColor = Color(0xffFF0000);
  static const Color darkred = Color(0xffBD0F0F);
  static const Color blackColor = Colors.black;
  static const Color black54Color = Colors.black54;
  // static const Color primaryColor = Color(0xff015C52);
  static const Color body_font_color = Color(0xff444444);
  static const Color card_color = Color(0xffE0F7CD);
  static const Color start_task = Color(0xff273819);
  static const Color end_task = Color(0xff630315);
  static const Color progress_task = Color(0xff0A31BF);

}
